### ISSUE TITLE
App for ios

### ISSUE THREAD

**Issue by Dvixe** [ScriptHelper/AversHenni#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

H

**Comment by ScriptHelper** [comment]
Can you explain what your problem is and how we can help you?

**Comment by ScriptHelper** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
> H

Can you explain what your problem is and how we can help you?

**Comment by ScriptHelper** [comment]
unable to figure out what your real problem is.

**Comment by ScriptHelper** [comment]
unable to figure out what your real problem is.
