### ISSUE TITLE
Not installed


### ISSUE THREAD

**Issue by Sudip909** [ScriptHelper/AversHenni#6]
App not installed in my phone,😐😐😐

**Comment by ScriptHelper** [comment]
?

**Comment by Sudip909** [comment]
I mean this app is not installe in my phone, and always say "sumthing went wrong" please fix it

**Comment by ScriptHelper** [comment]
> I mean this app is not installe in my phone, and always say "sumthing went wrong" please fix it

Screenshot please

**Comment by Sudip909** [comment]
![Screenshot_20220531-151437.png](https://user-images.githubusercontent.com/78501062/171144959-0d6052d2-d91e-4ed2-a54e-3ab3d4f404f9.png)


When I click the app only this option show

**Comment by ScriptHelper** [comment]
What is your phone's Android version?

Delete that app and download the apk from here. Then check.

https://t.me/F4SRobot?start=Z2V0LTgwMTMzODQ1MjQzMjg

**Comment by Sudip909** [comment]
Android version 7,and again same problem 🤧🤧🤧🤧 please fix it

**Comment by ScriptHelper** [comment]
> Android version 7,and again same problem 🤧🤧🤧🤧 please fix it


![Screenshot_2022-06-01-22-06-55-03_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/100191153/171449840-256b4a33-9f0f-4f25-8709-818712cc8306.jpg)

Android v7 not supported
